### ISSUE TITLE
v1.3.6 broken

### ISSUE THREAD

**Issue by rofe** [adobe/helix-googledocs2md#100]
**Description**
gdocs2md@1.3.6 turned out to be unusable.

**To Reproduce**
- open https://adobeioruntime.net/api/v1/web/helix/helix-services-private/gdocs2md@1.3.6/_status_check/healthcheck.json in your browser
- observe error message:
```json
{
  "code": "W3kPMC22VHZvvzmzrHvtgT0aAy8m7dlA",
  "error": "There was an error processing your request."
}
```
- run `wsk activation get 0f9417c72cc24fc29417c72cc2bfc2b7`
- observe error message:
"Initialization has failed due to: Error: Unable to expose method \"then\"\n    at Object.plumbing.exposePromiseMethod (/nodejsAction/XXJHjDeA/main.js:308900:19)\n    at ./node_modules/request-promise-core/configure/request2.js.module.exports (/nodejsAction/XXJHjDeA/main.js:308657:83)\n    at Object.<anonymous> (/nodejsAction/XXJHjDeA/main.js:308954:1)\n    at Object../node_modules/request-promise-native/lib/rp.js (/nodejsAction/XXJHjDeA/main.js:308967:30)\n    at __webpack_require__ (/nodejsAction/XXJHjDeA/main.js:30:30)\n    at Object../src/BlobHandler.js (/nodejsAction/XXJHjDeA/main.js:316270:12)\n    at __webpack_require__ (/nodejsAction/XXJHjDeA/main.js:30:30)\n    at Object../src/index.js (/nodejsAction/XXJHjDeA/main.js:317075:21)\n    at __webpack_require__ (/nodejsAction/XXJHjDeA/main.js:30:30)\n    at /nodejsAction/XXJHjDeA/main.js:94:18"

**Expected behavior**
No error in activation

**Version:**
1.3.6

**Additional context**
Production links for this action have been reset to 1.3.5 in order to restore the service."error":

**Comment by tripodsan** [comment]
the branch deploy step actually produces and error but didn't fail in CI:

```
Creating:  dist/helix-services-private/gdocs2md@ci408.zip
 - package.json
 - main.js
 1228294 total bytes
ok: created action: dist/helix-services-private/gdocs2md@ci408.zip.
Deploying dist/helix-services-private/gdocs2md@ci408.zip as helix-services-private/gdocs2md@ci408 to OpenWhisk
ok: updated action /helix/helix-services-private/gdocs2md@ci408

You can verify the action with:
$ curl "https://adobeioruntime.net/api/v1/web/helix/helix-services-private/gdocs2md@ci408"
--: requesting: https://adobeioruntime.net/api/v1/web/helix/helix-services-private/gdocs2md@ci408/_status_check/healthcheck.json ...
id: 4d67e0ac5d1d4a08a7e0ac5d1daa0864
error:  400 - "{\n  \"code\": \"DMYU9GALola6HbKEgZE1jDuzaHHBpLWi\",\n  \"error\": \"There was an error processing your request.\"\n}"
creating sequence: helix-services/gdocs2md@ci -> /helix/helix-services-private/gdocs2md@ci408
ok: created sequence /helix/helix-services/gdocs2md@ci -> /helix/helix-services-private/gdocs2md@ci408
{
  "name": "Release ci408",
  "url": "/helix/helix-services-private/gdocs2md@ci408"
}
```

**Comment by tripodsan** [comment]
fixed.
