### ISSUE TITLE
Single image in a section rendered with too many line breaks

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-googledocs2md#123]
In the gdoc, add an image in between 2 horizontal lines. Adding an horizontal line produce automatically a line break before and after. This renders as: 

```
---


![](https://hlx.blob.core.windows.net/external/...) 


---
```

If you manually remove the line breaks in between you still get extra line breaks for the image I assume:

```
---

![](https://hlx.blob.core.windows.net/external/...) 

---
``` 

In both cases, this will be transformed by our pipeline into: 

```
<div class="default">
   <p><img src="https://hlx.blob.core.windows.net/..."> </p>
</div>
```

while we need: 
```
<div class="image">
   <img src="https://hlx.blob.core.windows.net/...">
</div>
```
While this might be a pipeline issue, https://github.com/adobe/helix-word2md does not have those extra line breaks. We should align the 2 outputs to be similar.
See ("same" content in the docx / gdoc file):
- https://adobeioruntime.net/api/v1/web/helix/helix-services/gdocs2md@latest?rid=0aYfv3i%2BriejCOxd4ROWUcPx29Wya77D&src=helix%2Fgithub.com--davidnuescheler--theblog%2Fmaster&path=%2Fposts%2Fcreating-adobe-experience-platform-pipeline-with-kafka&rootId=1S59uiLis6nt6WUrNzdWHdwnt6kqTwxz8
- https://adobeioruntime.net/api/v1/web/helix/helix-services/word2md@latest?rid=KRl7fK%2BJVrmNpcbB4xnz%2F0w3XG6VqrAF&src=helix%2Fgithub.com--davidnuescheler--theblog%2Fproducts&path=%2Fposts%2Fcreating-adobe-experience-platform-pipeline-with-kafka.docx&shareLink=https%3A%2F%2Fadobe.sharepoint.com%2Fsites%2FTheBlog%2FShared%2520Documents%2Ftheblog%3Fcsf%3D1%26e%3D8Znxth

**Comment by kptdobe** [comment]
I traced it, this is an issue in the pipeline, the `data-hlx-types` is not correct the same for the gdoc than for the docx. Need to understand why.

**Comment by kptdobe** [comment]
Hummm.... there was one single white space after the image (certainly came after the copy/paste) which lead to a text node in the DOM. Thus image was not alone in the section.
No issue then, apart from the fact that we need to make the system much stronger in front of those kind of invisible characters.

cc @tripodsan @davidnuescheler FYI...

**Comment by tripodsan** [comment]
maybe related to #28
